### ISSUE TITLE
Build errors on kernel 6.1 and higher

### ISSUE THREAD

**Issue by philippfriese** [hpc/xpmem#62]
During build on a Kernel 6.4.2, the following error message appears:

```make
$ make
[...]
  CC [M]  /home/pfriese/build/xpmem/kernel/xpmem_attach.o
/home/pfriese/build/xpmem/kernel/xpmem_attach.c: In function ‘xpmem_attach’:
/home/pfriese/build/xpmem/kernel/xpmem_attach.c:510:62: error: ‘struct vm_area_struct’ has no member named ‘vm_next’
  510 |                                 ; existing_vma = existing_vma->vm_next) {
      |                                                              ^~
/home/pfriese/build/xpmem/kernel/xpmem_attach.c:530:23: error: assignment of read-only member ‘vm_flags’
  530 |         vma->vm_flags |=
[...]
```

The first issue originates from commit [763ecb0](https://github.com/torvalds/linux/commit/763ecb035029f500d7e6dc99acd1ad299b7726a1#diff-dc57f7b72015cf5f95444ec4f8a60f85d773f40b96ac59bf55b281cd63c06142) on 2022-09-27, titled "mm: remove the vma linked list".

The second issue originates from commit [bc292ab](https://github.com/torvalds/linux/commit/bc292ab00f6c7a661a8a605c714e8a148f629ef6#diff-dc57f7b72015cf5f95444ec4f8a60f85d773f40b96ac59bf55b281cd63c06142) on 2023-02-10, titled "mm: introduce vma->vm_flags wrapper functions".

**Comment by wenduwan** [comment]
I'm seeing the same issue on
```
Linux ip-172-31-32-95 6.2.0-1018-aws #18~22.04.1-Ubuntu SMP Wed Jan 10 22:31:58 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
```
